/**
 * Application error codes — UPPER_SNAKE_CASE, domain-prefixed.
 */
export const ERROR_CODES = {
  // General
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Auth
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  AUTHORIZATION_DENIED: 'AUTHORIZATION_DENIED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',

  // Contributor
  CONTRIBUTOR_NOT_FOUND: 'CONTRIBUTOR_NOT_FOUND',
  CONTRIBUTOR_ALREADY_EXISTS: 'CONTRIBUTOR_ALREADY_EXISTS',

  // Founding
  FOUNDING_STATUS_PERMANENT: 'FOUNDING_STATUS_PERMANENT',

  // Admission
  APPLICATION_NOT_FOUND: 'APPLICATION_NOT_FOUND',
  APPLICATION_ALREADY_EXISTS: 'APPLICATION_ALREADY_EXISTS',
  DOMAIN_MICRO_TASK_NOT_FOUND: 'DOMAIN_MICRO_TASK_NOT_FOUND',
  GDPR_CONSENT_REQUIRED: 'GDPR_CONSENT_REQUIRED',
  REVIEWER_ALREADY_ASSIGNED: 'REVIEWER_ALREADY_ASSIGNED',
  APPLICATION_ALREADY_REVIEWED: 'APPLICATION_ALREADY_REVIEWED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  REVIEWER_NOT_FOUND: 'REVIEWER_NOT_FOUND',
  APPLICATION_NOT_REVIEWABLE: 'APPLICATION_NOT_REVIEWABLE',

  // Health
  HEALTH_CHECK_FAILED: 'HEALTH_CHECK_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
