/**
 * Application error codes — UPPER_SNAKE_CASE, domain-prefixed.
 */
export const ERROR_CODES = {
  // General
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // Auth
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  AUTHORIZATION_DENIED: 'AUTHORIZATION_DENIED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',

  // Contributor
  CONTRIBUTOR_NOT_FOUND: 'CONTRIBUTOR_NOT_FOUND',
  CONTRIBUTOR_ALREADY_EXISTS: 'CONTRIBUTOR_ALREADY_EXISTS',

  // Founding
  FOUNDING_STATUS_PERMANENT: 'FOUNDING_STATUS_PERMANENT',

  // Admission
  APPLICATION_NOT_FOUND: 'APPLICATION_NOT_FOUND',
  APPLICATION_ALREADY_EXISTS: 'APPLICATION_ALREADY_EXISTS',
  DOMAIN_MICRO_TASK_NOT_FOUND: 'DOMAIN_MICRO_TASK_NOT_FOUND',
  GDPR_CONSENT_REQUIRED: 'GDPR_CONSENT_REQUIRED',
  REVIEWER_ALREADY_ASSIGNED: 'REVIEWER_ALREADY_ASSIGNED',
  APPLICATION_ALREADY_REVIEWED: 'APPLICATION_ALREADY_REVIEWED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  REVIEWER_NOT_FOUND: 'REVIEWER_NOT_FOUND',
  APPLICATION_NOT_REVIEWABLE: 'APPLICATION_NOT_REVIEWABLE',

  // Micro-task admin
  MICRO_TASK_NOT_FOUND: 'MICRO_TASK_NOT_FOUND',
  MICRO_TASK_DOMAIN_ACTIVE_EXISTS: 'MICRO_TASK_DOMAIN_ACTIVE_EXISTS',

  // Buddy assignment
  BUDDY_NOT_FOUND: 'BUDDY_NOT_FOUND',
  NO_ELIGIBLE_BUDDIES: 'NO_ELIGIBLE_BUDDIES',
  BUDDY_ALREADY_ASSIGNED: 'BUDDY_ALREADY_ASSIGNED',
  BUDDY_ASSIGNMENT_EXPIRED: 'BUDDY_ASSIGNMENT_EXPIRED',

  // Onboarding
  MILESTONE_ALREADY_COMPLETED: 'MILESTONE_ALREADY_COMPLETED',
  INVALID_MILESTONE_TYPE: 'INVALID_MILESTONE_TYPE',
  ONBOARDING_NOT_STARTED: 'ONBOARDING_NOT_STARTED',

  // Ingestion
  REPOSITORY_NOT_FOUND: 'REPOSITORY_NOT_FOUND',
  REPOSITORY_ALREADY_MONITORED: 'REPOSITORY_ALREADY_MONITORED',
  WEBHOOK_REGISTRATION_FAILED: 'WEBHOOK_REGISTRATION_FAILED',
  WEBHOOK_DEREGISTRATION_FAILED: 'WEBHOOK_DEREGISTRATION_FAILED',
  WEBHOOK_VALIDATION_FAILED: 'WEBHOOK_VALIDATION_FAILED',
  GITHUB_API_ERROR: 'GITHUB_API_ERROR',
  GITHUB_RATE_LIMITED: 'GITHUB_RATE_LIMITED',
  CONTRIBUTION_INGESTION_FAILED: 'CONTRIBUTION_INGESTION_FAILED',
  DUPLICATE_WEBHOOK_DELIVERY: 'DUPLICATE_WEBHOOK_DELIVERY',
  CONTRIBUTOR_NOT_FOUND_FOR_GITHUB_USER: 'CONTRIBUTOR_NOT_FOUND_FOR_GITHUB_USER',

  // Collaboration
  COLLABORATION_NOT_FOUND: 'COLLABORATION_NOT_FOUND',
  COLLABORATION_ALREADY_CONFIRMED: 'COLLABORATION_ALREADY_CONFIRMED',
  ATTRIBUTION_SPLIT_INVALID: 'ATTRIBUTION_SPLIT_INVALID',
  ATTRIBUTION_OVERRIDE_UNAUTHORIZED: 'ATTRIBUTION_OVERRIDE_UNAUTHORIZED',

  // Working Groups
  WORKING_GROUP_NOT_FOUND: 'WORKING_GROUP_NOT_FOUND',
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  NOT_A_MEMBER: 'NOT_A_MEMBER',

  // Tasks
  TASK_NOT_FOUND: 'TASK_NOT_FOUND',
  TASK_ALREADY_CLAIMED: 'TASK_ALREADY_CLAIMED',
  INVALID_TASK_TRANSITION: 'INVALID_TASK_TRANSITION',
  TASK_NOT_CLAIMABLE: 'TASK_NOT_CLAIMABLE',
  TASK_NOT_OWNED: 'TASK_NOT_OWNED',
  TASK_CREATION_FORBIDDEN: 'TASK_CREATION_FORBIDDEN',

  // Announcements
  ANNOUNCEMENT_TOO_LONG: 'ANNOUNCEMENT_TOO_LONG',
  NOT_WORKING_GROUP_LEAD: 'NOT_WORKING_GROUP_LEAD',
  ANNOUNCEMENT_NOT_FOUND: 'ANNOUNCEMENT_NOT_FOUND',

  // Activity
  ACTIVITY_FEED_UNAVAILABLE: 'ACTIVITY_FEED_UNAVAILABLE',
  ACTIVITY_SSE_CONNECTION_FAILED: 'ACTIVITY_SSE_CONNECTION_FAILED',

  // Notifications
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_ACCESS_DENIED: 'NOTIFICATION_ACCESS_DENIED',

  // Feedback
  FEEDBACK_NOT_FOUND: 'FEEDBACK_NOT_FOUND',
  FEEDBACK_ALREADY_ASSIGNED: 'FEEDBACK_ALREADY_ASSIGNED',
  NO_ELIGIBLE_REVIEWER: 'NO_ELIGIBLE_REVIEWER',
  FEEDBACK_ACCESS_DENIED: 'FEEDBACK_ACCESS_DENIED',
  FEEDBACK_ALREADY_SUBMITTED: 'FEEDBACK_ALREADY_SUBMITTED',
  FEEDBACK_INVALID_STATUS: 'FEEDBACK_INVALID_STATUS',
  FEEDBACK_REASSIGN_SAME_REVIEWER: 'FEEDBACK_REASSIGN_SAME_REVIEWER',

  // Evaluation
  EVALUATION_NOT_FOUND: 'EVALUATION_NOT_FOUND',
  EVALUATION_ALREADY_EXISTS: 'EVALUATION_ALREADY_EXISTS',
  EVALUATION_MODEL_UNAVAILABLE: 'EVALUATION_MODEL_UNAVAILABLE',
  EVALUATION_FAILED: 'EVALUATION_FAILED',
  EVALUATION_MODEL_NOT_FOUND: 'EVALUATION_MODEL_NOT_FOUND',
  EVALUATION_RUBRIC_NOT_FOUND: 'EVALUATION_RUBRIC_NOT_FOUND',

  // Health
  HEALTH_CHECK_FAILED: 'HEALTH_CHECK_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
